export default function MisinfoAlert({ misinformation, sourcePosts }) {
  if (!misinformation || misinformation.flagged_count === 0) return null;

  const flaggedPosts = sourcePosts
    ? sourcePosts.filter((p) => p.misinfo && p.misinfo.is_flagged)
    : [];

  return (
    <div className="glass-card full-width misinfo-card">
      <div className="card-header">
        <div className="card-icon" style={{ background: 'rgba(239, 68, 68, 0.15)' }}>🚨</div>
        <div>
          <div className="card-title">Misinformation Alerts</div>
          <div className="card-subtitle">
            {misinformation.flagged_count} of {misinformation.total_posts} discussions flagged
          </div>
        </div>
      </div>

      <div className="misinfo-summary">
        <div className="misinfo-stat">
          <div className="misinfo-stat-value" style={{ color: '#ef4444' }}>
            {misinformation.flagged_pct}%
          </div>
          <div className="misinfo-stat-label">Flagged Rate</div>
        </div>
        {misinformation.top_reasons && misinformation.top_reasons.length > 0 && (
          <div className="misinfo-reasons">
            <div style={{ fontSize: 12, color: '#94a3b8', marginBottom: 6 }}>Detection Reasons:</div>
            {misinformation.top_reasons.map((reason, i) => (
              <div key={i} className="misinfo-reason-tag">
                ⚠️ {reason}
              </div>
            ))}
          </div>
        )}
      </div>

      {flaggedPosts.length > 0 && (
        <div className="misinfo-posts">
          <div style={{ fontSize: 12, color: '#94a3b8', marginBottom: 8 }}>Flagged Discussions:</div>
          {flaggedPosts.slice(0, 5).map((post, i) => (
            <div key={i} className="misinfo-post-item">
              <div className="misinfo-post-header">
                <span className={`source-badge ${post.source.toLowerCase()}`}>{post.source}</span>
                <span className="misinfo-flag-badge">⚠️ Flagged</span>
              </div>
              <div className="misinfo-post-text">{post.text}</div>
              {post.misinfo.reasons && post.misinfo.reasons.length > 0 && (
                <div className="misinfo-post-reasons">
                  {post.misinfo.reasons.map((r, j) => (
                    <span key={j} className="misinfo-mini-tag">{r}</span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      <div className="misinfo-disclaimer">
        ℹ️ Flags are generated by automated pattern detection. Always consult healthcare professionals
        for medical advice.
      </div>
    </div>
  );
}
